name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

schedules:
  - cron: "0 2 * * *"
    displayName: Daily PR cleanup
    branches:
      include:
        - master
    always: true

jobs:
  - job: build
    displayName: Cleanup ECS PR Proxies
    timeoutInMinutes: 240
    pool:
      name: 'AWS-ECS'

    workspace:
      clean: all

    steps:

      - checkout: self

      - bash: |
          instance_id="$(curl -s http://169.254.169.254/latest/meta-data/instance-id)"
          echo instance-id: "${instance_id}"
          echo connect to: https://eu-west-2.console.aws.amazon.com/systems-manager/session-manager/${instance_id}
          echo sudo su - ubuntu
          echo working directory: $(System.DefaultWorkingDirectory)
        displayName: print aws info

      - template: ./components/aws-assume-role.yml
         parameters:
           role: "auto-ops"
           profile: "apm_ptl"

      - bash: |
          tfenv use 0.14.6
        displayName: setup terraform

      - bash: |
          make install
        displayName: install dependencies

      - bash: |
          export retain_hours=72
          ANSIBLE_FORCE_COLOR=yes make -C ansible remove-old-ecs-pr-deploys
        displayName: "cleanup older pr deploys"
