parameters:
  - name: jinja_templates
    type: object
  - name: depends_on
    type: object
  - name: stage_name
  - name: apigee_organization
  - name: environment
    values:
      - internal-dev
      - internal-dev-sandbox
      - internal-qa
      - internal-qa-sandbox
      - ref
      - dev
      - int
      - sandbox
      - prod
  - name: aws_env_account
  - name: aws_org_account
  - name: service_name
  - name: short_service_name
  - name: fully_qualified_service_name
  - name: service_base_path
  - name: secret_ids
    type: object
  - name: config_ids
    type: object
  - name: proxy_path
  - name: product_display_name
  - name: product_description
  - name: spec_file
    type: string
  - name: portal_api_requires_callback_url
    type: boolean
  - name: make_spec_visible
    type: boolean
  - name: friendly_api_name
    type: string
  - name: ping
    type: boolean
  - name: pre_template
    type: stepList
  - name: post_template
    type: stepList
  - name: pre_deploy
    type: stepList
  - name: post_deploy
    type: stepList
  - name: notify
    type: boolean
    default: false
  - name: enable_monitoring
    type: boolean

stages:
  - stage: ${{ parameters.stage_name }}
    dependsOn: ${{ parameters.depends_on }}
    jobs:
      - deployment: deploy
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none

                - task: DownloadPipelineArtifact@2
                  inputs:
                    source: "specific"
                    project: $(resources.pipeline.build_pipeline.projectID)
                    pipeline: $(resources.pipeline.build_pipeline.pipelineID)
                    preferTriggeringPipeline: true
                    runVersion: "latestFromBranch"
                    runBranch: $(Build.SourceBranch)
                    path: "$(Pipeline.Workspace)/s/${{ parameters.service_name }}"

                - bash: |
                    echo "$(Build.SourceVersion)"
                    echo "$(Build.SourceVersionMessage)"
                    echo "$(resources.pipeline.build_pipeline.sourceCommit)"

                - task: DownloadSecureFile@1
                  name: aws_config
                  inputs:
                    secureFile: ptl_aws_config

                - bash: |
                    set -euo pipefail
                    mkdir -p ~/.aws
                    mv $(aws_config.secureFilePath) ~/.aws/config
                    chmod 400 ~/.aws/config
                    ls -al ~/.aws/config
                  displayName: "Get AWS config"

                - task: UsePythonVersion@0
                  displayName: 'Use Python 3.8'
                  inputs:
                    versionSpec: 3.8

                - bash: "python -m pip install --upgrade pip setuptools wheel && pip install poetry"
                  displayName: Install python dependencies

                - template: "../components/set-facts.yml"
                  parameters:
                    service_name: ${{ parameters.service_name }}
                    secret_ids:
                      - ${{ parameters.aws_org_account }}/azure-devops/apigee-${{ parameters.apigee_organization }}/APIGEE_OTP_KEY
                      - ${{ parameters.aws_org_account }}/azure-devops/apigee-${{ parameters.apigee_organization }}/APIGEE_PASSWORD
                      - ${{ parameters.aws_org_account }}/azure-devops/MONITORING_API_KEY
                      - ptl/access-tokens/github/repo-status-update/GITHUB_ACCESS_TOKEN
                      - ${{ each secret_id in parameters.secret_ids }}:
                          - ${{ secret_id }}
                    config_ids:
                      - /${{ parameters.aws_org_account }}/azure-devops/apigee-${{ parameters.apigee_organization }}/APIGEE_USERNAME
                      - /${{ parameters.aws_env_account }}/azure-devops/env-${{ parameters.environment }}/ENV_URL
                      - /${{ parameters.aws_env_account }}/azure-devops/env-${{ parameters.environment }}/IDENTITY_URL
                      - /ptl/azure-devops/GITHUB_USER
                      - ${{ each config_id in parameters.config_ids }}:
                          - ${{ config_id }}

                - ${{ if parameters.notify }}:
                  - bash: |
                      export COMMIT_SHA=`echo "$(Build.SourceVersionMessage)" | cut -d' ' -f2`
                      echo "##vso[task.setvariable variable=COMMIT_SHA]$COMMIT_SHA"
                    displayName: Set COMMIT_SHA

                  - template: '../components/update-github-status.yml'
                    parameters:
                      state: pending
                      description: "Deploy to ${{ parameters.environment }} started"

                - template: "../components/expose-pipeline-values.yml"
                  parameters:
                    expose:
                      apigee_environment: ${{ parameters.environment }}
                      fully_qualified_service_name: ${{ parameters.fully_qualified_service_name }}

                - template: "../templates/deploy-service.yml"
                  parameters:
                    service_name: ${{ parameters.service_name }}
                    short_service_name: ${{ parameters.short_service_name }}
                    fully_qualified_service_name: ${{ parameters.fully_qualified_service_name }}
                    service_base_path: ${{ parameters.service_base_path }}
                    jinja_templates: ${{ parameters.jinja_templates }}
                    apigee_environment: ${{ parameters.environment }}
                    apigee_organization: ${{ parameters.apigee_organization }}
                    product_display_name: ${{ parameters.product_display_name }}
                    product_description: ${{ parameters.product_description }}
                    proxy_path: ${{ parameters.proxy_path }}
                    pre_template: ${{ parameters.pre_template }}
                    post_template: ${{ parameters.post_template }}
                    pre_deploy: ${{ parameters.pre_deploy }}
                    post_deploy: ${{ parameters.post_deploy }}
                    ping: ${{ parameters.ping }}
                    enable_monitoring: ${{ parameters.enable_monitoring }}

                - ${{ if ne(parameters.spec_file, '') }}:
                  - template: "../templates/deploy-spec.yml"
                    parameters:
                      spec_file: ${{ parameters.spec_file }}
                      service_name: ${{ parameters.service_name }}
                      apigee_environment: ${{ parameters.environment }}
                      apigee_organization: ${{ parameters.apigee_organization }}
                      fully_qualified_service_name: ${{ parameters.fully_qualified_service_name }}
                      portal_api_requires_callback_url: ${{ parameters.portal_api_requires_callback_url }}
                      make_spec_visible: ${{ parameters.make_spec_visible }}
                      friendly_api_name: ${{ parameters.friendly_api_name }}

                - ${{ if parameters.notify }}:
                  - template: '../components/update-github-status.yml'
                    parameters:
                      state: success
                      on_success: true
                      description: "Deploy to ${{ parameters.environment }} succeeded"

                  - template: '../components/update-github-status.yml'
                    parameters:
                      state: failure
                      on_failure: true
                      description: "Deploy to ${{ parameters.environment }} failed"
