account = "{{ account }}"
profile = "{{ aws_profile }}"
workspace = "{{ workspace }}"
service_name= "{{ service_name }}"
apigee_environment = "{{ apigee_environment }}"
namespace = "{{ sub_namespace }}"
state_bucket = "nhsd-apm-management-{{ account }}-terraform"