- name: create api deployment pre-reqs
  hosts: 127.0.0.1
  connection: local
  gather_facts: no

  vars:
    service_id: "{{ lookup('env','service_id') }}"
    APIGEE_ENVIRONMENT: "{{ lookup('env','APIGEE_ENVIRONMENT') }}"
    pr_number: "{{ lookup('env','pr_number') }}"
    account:  "{{ lookup('env','account') }}"
    aws_profile: "apm_{{ account }}"

  pre_tasks:

    - name: check account
      fail:
        msg: "account not set"
      when: not account

    - name: check service_id
      fail:
        msg: "service_id not set"
      when: not service_id

    - name: check APIGEE_ENVIRONMENT
      fail:
        msg: "APIGEE_ENVIRONMENT not set"
      when: not APIGEE_ENVIRONMENT

  roles:
    - setup-facts
    - create-api-deployment-pre-reqs
